frontend:
  image: vergilken111/frontend
  tag: 0640b3b
  autoscaling:
    averageUtilization: 90
backend:
  image: vergilken111/backend
  tag: 0640b3b
  autoscaling:
    averageUtilization: 90
database:
  enabled: true
  uri: pg-service
  username: postgres
  password: postgres
